name: RPUniverse
version: '${project.version}'
main: me.fami6xx.rpuniverse.RPUniverse
softdepend: [ DecentHolograms ]
authors: [ Fami6Xx ]
description: A unique plugin that allows you to create your own Role play world
commands:
  me:
    description: Sends a message acting as a animation
    usage: /<command> <message>
    permission: rpu.me
  do:
    description: Sends a message acting as some kind of player status
    usage: /<command> <message>
    permission: rpu.do