name: RPUniverse
version: '${project.version}'
main: me.fami6xx.rpuniverse.RPUniverse
softdepend: [ DecentHolograms, Vault, PlaceholderAPI ]
authors: [ Fami6Xx ]
description: A unique plugin that allows you to create your own Role play world
commands:
  me:
    description: Sends a message acting as a animation
    usage: /<command> <message>
    permission: rpu.me
  do:
    description: Sends a message acting as some kind of temporary player status
    usage: /<command> <message>
    permission: rpu.do
  status:
    description: Sends a message acting as some kind of player status
    usage: /<command> <message>
    permission: rpu.status
  stopstatus:
    description: Stops the status
    usage: /<command>
    permission: rpu.stopstatus
  createjob:
    description: Starts the process of creating a job
    usage: /<command>
    permission: rpu.createjob
  jobs:
    description: Lists all jobs
    usage: /<command>
    permission: rpu.jobs

permissions:
  rpu.user:
    description: Gives access to all user commands
    default: true
    children:
        rpu.me: true
        rpu.do: true
        rpu.status: true
        rpu.stopstatus: true
  rpu.admin:
    description: Gives access to all admin commands
    children:
        rpu.createjob: true
        rpu.jobs: true
