name: RPUniverse
version: '${project.version}'
main: me.fami6xx.rpuniverse.RPUniverse
softdepend: [ DecentHolograms, Vault, PlaceholderAPI ]
author: Fami6Xx
description: A unique plugin that allows you to create your own Role play world
website: https://github.com/Fami6Xx
api-version: '1.13'
libraries:
  - 'com.google.code.gson:gson:2.10.1'
commands:
  me:
    description: Sends a message acting as a animation
    usage: /<command> <message>
    permission: rpu.me
  do:
    description: Sends a message acting as some kind of temporary player status
    usage: /<command> <message>
    permission: rpu.do
  status:
    description: Sends a message acting as some kind of player status
    usage: /<command> <message>
    permission: rpu.status
  stopstatus:
    description: Stops the status
    usage: /<command>
    permission: rpu.stopstatus
  createjob:
    description: Starts the process of creating a job
    usage: /<command>
  jobs:
    description: Lists all jobs
    usage: /<command>
  modmode:
    description: Toggles the modmode
    usage: /<command> (player)
    aliases: [mmode, mm]
  adminmode:
    description: Toggles the adminmode
    usage: /<command> (player)
    aliases: [amode, am]
  tag:
    description: Shows the set tag of a player
    usage: /<command>
  settag:
    description: Sets the tag of a player
    usage: /<command> <player> <tag>
  globalooc:
    description: Sends a message to the global OOC chat
    usage: /<command> <message>
  switchjob:
    description: Switches the job of a player
    usage: /<command> (jobId)
permissions:
  rpu.user:
    description: Gives access to all user commands
    children:
        rpu.me: true
        rpu.do: true
        rpu.status: true
        rpu.stopstatus: true
        rpu.globalooc: true
  rpu.admin:
    description: Gives access to all admin commands
    children:
        rpu.createjob: true
        rpu.jobs: true
        rpu.modmode: true
        rpu.adminmode: true
        rpu.tag: true
        rpu.settag: true
  rpu.multiplejobs:
    description: Allows the player to have multiple jobs (if enabled in the config)
  rpu.me:
    description: Allows the player to use the /me command
  rpu.do:
    description: Allows the player to use the /do command
  rpu.status:
    description: Allows the player to use the /status command
  rpu.stopstatus:
    description: Allows the player to use the /stopstatus command
  rpu.createjob:
    description: Allows the player to use the /createjob command
  rpu.jobs:
    description: Allows the player to use the /jobs command
  rpu.modmode:
    description: Allows the player to use the /modmode command
  rpu.adminmode:
    description: Allows the player to use the /adminmode command
  rpu.tag:
    description: Allows the player to use the /tag command
  rpu.settag:
    description: Allows the player to use the /settag command
  rpu.globalooc:
    description: Allows the player to use the global ooc chat