name: RPUniverse
version: '${project.version}'
main: me.fami6xx.rpuniverse.RPUniverse
softdepend: [ DecentHolograms, Vault, PlaceholderAPI ]
author: Fami6Xx
description: A unique plugin that allows you to create your own Role play world
website: https://github.com/Fami6Xx
api-version: '1.14'
libraries:
  - 'com.google.code.gson:gson:2.10.1'
commands:
  me:
    description: Sends a message acting as a animation
    usage: /<command> <message>
    permission: rpu.me
  do:
    description: Sends a message acting as some kind of temporary player status
    usage: /<command> <message>
    permission: rpu.do
  doc:
    description: Sends a message and a hologram that acts as if player is doing something for some period of time
    usage: /<command> <seconds> (message)
    permission: rpu.doc
  try:
    description: Sends a message that has 50% chance of saing no or yes
    usage: /<command>
    permission: rpu.try
  status:
    description: Sends a message acting as some kind of player status
    usage: /<command> <message>
    permission: rpu.status
  stopstatus:
    description: Stops the status
    usage: /<command>
    permission: rpu.stopstatus
  createjob:
    description: Starts the process of creating a job
    usage: /<command>
  jobs:
    description: Lists all jobs
    usage: /<command>
  modmode:
    description: Toggles the modmode
    usage: /<command> (player)
    aliases: [mmode, mm]
  adminmode:
    description: Toggles the adminmode
    usage: /<command> (player)
    aliases: [amode, am]
  tag:
    description: Shows the set tag of a player
    usage: /<command>
  settag:
    description: Sets the tag of a player
    usage: /<command> <player> <tag>
  globalooc:
    description: Sends a message to the global OOC chat
    usage: /<command> <message>
    aliases: [ooc, gchat, globalchat, gooc, go]
  switchjob:
    description: Switches the job of a player
    usage: /<command> (jobId)
  consumables:
    description: Opens the consumables menu
    usage: /<command>
    aliases: [consumable, consumablemenu, basicneeds, basicneedsmenu]
  poop:
    description: Command used to empty the poop from basic needs
    usage: /<command>
  pee:
    description: Command used to empty the pee from basic needs
    usage: /<command>
  locks:
    description: Opens the locks menu
    usage: /<command>
    aliases: [lock, lockmenu]
  pay:
    description: Pays another player
    usage: /<command> <player> <amount>
    permission: rpu.pay
  rpuniverse:
    description: Main command of the plugin
    usage: /<command> <subcommand>
    aliases: [rpu]
  properties:
    description: Opens the properties menu
    usage: /<command>
    aliases: [property, propertymenu]
  invoices:
    description: Opens the invoice menu
    usage: /<command> [received|created|job]
    permission: rpu.invoices.view
  createinvoice:
    description: Creates an invoice for another player
    usage: /<command> <player> <amount>
    permission: rpu.invoices.create
permissions:
  rpu.user:
    description: Gives access to all user commands (me, do, doc, try, status, globalooc, pay, invoices)
    children:
        rpu.me: true
        rpu.do: true
        rpu.status: true
        rpu.stopstatus: true
        rpu.globalooc: true
        rpu.doc: true
        rpu.try: true
        rpu.pay: true
        rpu.invoices.view: true
        rpu.invoices.create: true
  rpu.admin:
    description: Gives access to all admin commands
    children:
        rpu.createjob: true
        rpu.jobs: true
        rpu.modmode: true
        rpu.adminmode: true
        rpu.tag: true
        rpu.settag: true
        rpu.user: true
        rpu.core.command: true
        rpu.properties: true
        rpu.invoices.view.job: true
        rpu.invoices.delete.job: true
  rpu.multiplejobs:
    description: Allows the player to have multiple jobs (if enabled in the config)
  rpu.me:
    description: Allows the player to use the /me command
  rpu.do:
    description: Allows the player to use the /do command
  rpu.try:
    description: Allows the player to use the /try command
  rpu.status:
    description: Allows the player to use the /status command
  rpu.stopstatus:
    description: Allows the player to use the /stopstatus command
  rpu.createjob:
    description: Allows the player to use the /createjob command
  rpu.jobs:
    description: Allows the player to use the /jobs command
  rpu.modmode:
    description: Allows the player to use the /modmode command
  rpu.adminmode:
    description: Allows the player to use the /adminmode command
  rpu.tag:
    description: Allows the player to use the /tag command
  rpu.settag:
    description: Allows the player to use the /settag command
  rpu.globalooc:
    description: Allows the player to use the global ooc chat
  rpu.basicneeds.edit:
    description: Allows the player to go to the /consumables menu
  rpu.core.command:
    description: Allows the player to use the /rpu command
  rpu.properties:
    description: Allows the player to use the /properties command
  rpu.pay:
    description: Allows the player to use the /pay command
  rpu.invoices.view:
    description: Allows the player to view their invoices
  rpu.invoices.view.job:
    description: Allows the player to view all invoices for their job
  rpu.invoices.delete.job:
    description: Allows the player to delete invoices for their job
  rpu.invoices.create:
    description: Allows the player to create invoices
