name: Build and Update Polymart + Modrinth Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g. v1.2.3 or 1.2.3)'
        required: true
      title:
        description: 'Release title'
        required: true
      message:
        description: 'Release message'
        required: true

jobs:
  build-and-upload:
    # Run if not a release event (workflow_dispatch) or if release.prerelease is false.
    if: ${{ github.event_name != 'release' || github.event.release.prerelease == false }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Prepare artifact for upload
        run: |
          mkdir staging
          echo "Copying non-shaded JAR files..."
          for file in target/*.jar; do
            if [[ "$file" != *-shaded* ]]; then
              echo "Copying $file"
              cp "$file" staging
            else
              echo "Skipping $file (shaded file)"
            fi
          done
            
      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@2.0.0
        with:
          api-domain: "staging-api.modrinth.com"
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ secrets.MODRINTH_PROJECT_ID }}
          name: ${{ github.event.release.name || github.event.inputs.title }}
          version: ${{ github.event.release.tag_name || github.event.inputs.version }}
          changelog: ${{ github.event.release.body || github.event.inputs.message }}
          loaders: |-
            paper
            purpur
          game-versions: |-
            1.14.x
            1.15.x
            1.16.x
            1.17.x
            1.18.x
            1.19.x
            1.20.x
            1.21.x
          files: '["${{ steps.artifact.outputs.file }}"]'
